package com.example.vex360.shared.exceptions;

import org.springframework.http.HttpStatus;

import lombok.Getter;

@Getter
public enum ErrorCode {
    // SYSTEM ERRORS
    UNCATCHED_EXCEPTION("SYS-001", "Đã có lỗi hệ thống xảy ra. Vui lòng thử lại sau.",
            HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_KEY("SYS-002", "Mã lỗi không hợp lệ.", HttpStatus.BAD_REQUEST),
    VALIDATION_FAILED("SYS-003", "Dữ liệu nhập vào không hợp lệ.", HttpStatus.UNPROCESSABLE_CONTENT),

    METHOD_NOT_ALLOWED("SYS-004", "Phương thức HTTP không được hỗ trợ.", HttpStatus.METHOD_NOT_ALLOWED),
    REGISTRATION_ALREADY_EXISTS("REGISTRATION-002",
            "Doanh nghiệp đã có một lượt đăng ký đang hoạt động cho sự kiện này.",
            HttpStatus.CONFLICT),

    // AUTH ERRORS
    UNAUTHENTICATED("AUTH-001", "Phiên đăng nhập đã hết hạn hoặc không hợp lệ. Vui lòng đăng nhập lại.",
            HttpStatus.UNAUTHORIZED),
    UNAUTHORIZED("AUTH-002", "Bạn không có quyền thực hiện thao tác này.", HttpStatus.FORBIDDEN),
    BAD_CREDENTIALS("AUTH-003", "Email hoặc mật khẩu không chính xác.", HttpStatus.UNAUTHORIZED),
    ACCOUNT_LOCKED("AUTH-004", "Tài khoản của bạn đã bị khóa. Vui lòng liên hệ quản trị viên.",
            HttpStatus.UNAUTHORIZED),
    ACCOUNT_DISABLED("AUTH-005", "Tài khoản của bạn đã bị vô hiệu hóa.", HttpStatus.UNAUTHORIZED),
    ACCOUNT_PENDING("AUTH-006", "Tài khoản chưa được kích hoạt. Vui lòng kiểm tra email để hoàn tất kích hoạt.",
            HttpStatus.UNAUTHORIZED),
    PROVIDER_NOT_SUPPORT_CHANGE_PASSWORD("AUTH-007",
            "Tài khoản đăng nhập qua dịch vụ bên ngoài không hỗ trợ đổi mật khẩu.",
            HttpStatus.BAD_REQUEST),
    PROVIDER_NOT_SUPPORT_FORGOT_PASSWORD("AUTH-008",
            "Tài khoản của bạn đã được đăng ký qua Google và không hỗ trợ quên mật khẩu. Vui lòng đăng nhập lại bằng Google.",
            HttpStatus.BAD_REQUEST),

    // BUSINESS ERRORS
    USER_NOT_FOUND("USER-001", "Không tìm thấy thông tin người dùng.", HttpStatus.NOT_FOUND),
    EMAIL_ALREADY_EXISTS("USER-002", "Email này đã được sử dụng.", HttpStatus.CONFLICT),
    ROLE_NOT_FOUND("USER-003", "Không tìm thấy vai trò người dùng.", HttpStatus.NOT_FOUND),
    FILE_SIZE_EXCEEDED("FILE-001", "Kích thước tệp vượt quá dung lượng cho phép (tối đa 10MB).",
            HttpStatus.BAD_REQUEST),
    FILE_TYPE_NOT_SUPPORTED("FILE-002", "Định dạng tệp không được hỗ trợ.", HttpStatus.BAD_REQUEST),
    NOT_A_PANORAMA("FILE-003", "Tệp tải lên không phải là ảnh panorama 360 hợp lệ.", HttpStatus.BAD_REQUEST),
    UPLOAD_FAILED("FILE-004", "Tải tệp lên không thành công. Vui lòng thử lại.", HttpStatus.INTERNAL_SERVER_ERROR),
    FILE_TOO_LARGE("FILE-005", "Dung lượng tệp vượt quá giới hạn cho phép (tối đa 10MB).",
            HttpStatus.CONTENT_TOO_LARGE),
    STORAGE_QUOTA_EXCEEDED("FILE-006", "Dung lượng lưu trữ của doanh nghiệp đã đầy. Vui lòng nâng cấp gói lưu trữ.",
            HttpStatus.CONTENT_TOO_LARGE),
    PANORAMA_FILE_REQUIRED(
            "FILE-007",
            "Vui lòng chọn một tệp ảnh panorama để tải lên.",
            HttpStatus.BAD_REQUEST),
    PANORAMA_FORMAT_NOT_SUPPORTED(
            "FILE-008",
            "Ảnh panorama chỉ hỗ trợ định dạng JPEG, PNG hoặc WEBP.",
            HttpStatus.UNSUPPORTED_MEDIA_TYPE),
    PANORAMA_IMAGE_CONTENT_INVALID(
            "FILE-009",
            "Tệp tải lên không phải là ảnh panorama hợp lệ hoặc nội dung tệp không khớp với định dạng đã khai báo.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    PANORAMA_ASPECT_RATIO_INVALID(
            "FILE-010",
            "Ảnh panorama phải có tỉ lệ chính xác 2:1, trong đó chiều rộng bằng hai lần chiều cao.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    PANORAMA_RESOLUTION_EXCEEDED(
            "FILE-011",
            "Độ phân giải ảnh panorama vượt quá giới hạn cho phép 8192 × 4096 pixel.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    STORAGE_PACKAGE_NOT_FOUND("STORAGE-001", "Không tìm thấy gói lưu trữ.", HttpStatus.NOT_FOUND),
    STORAGE_PACKAGE_ORDER_NOT_FOUND("STORAGE-002", "Không tìm thấy đơn hàng gói lưu trữ.", HttpStatus.NOT_FOUND),
    STORAGE_PACKAGE_NAME_DUPLICATED("STORAGE-003", "Tên gói lưu trữ đã tồn tại trong hệ thống.", HttpStatus.CONFLICT),
    STORAGE_PACKAGE_INACTIVE("STORAGE-005", "Gói lưu trữ này hiện không còn được mở bán.",
            HttpStatus.CONFLICT),
    STORAGE_PACKAGE_ORDER_SNAPSHOT_MISSING("STORAGE-006",
            "Đơn hàng lưu trữ thiếu thông tin dung lượng tại thời điểm mua. Vui lòng liên hệ quản trị viên.",
            HttpStatus.CONFLICT),
    STORAGE_USAGE_AMOUNT_INVALID("STORAGE-007", "Giá trị dung lượng lưu trữ không được âm.", HttpStatus.CONFLICT),
    STORAGE_RESERVED_USAGE_INSUFFICIENT("STORAGE-008", "Dung lượng đã giữ chỗ không đủ cho thao tác này.",
            HttpStatus.CONFLICT),
    STORAGE_PACKAGE_STATUS_FILTER_INVALID("STORAGE-009", "Bộ lọc trạng thái gói lưu trữ không hợp lệ.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    INPUT_FAILED("USER-004", "Dữ liệu nhập vào không hợp lệ.", HttpStatus.BAD_REQUEST),
    OLDPASSWORD_FAILED("USER-005", "Mật khẩu hiện tại không chính xác.", HttpStatus.BAD_REQUEST),

    INVALID_STORAGE_USAGE("STORAGE-004", "Trạng thái dung lượng lưu trữ không hợp lệ.", HttpStatus.CONFLICT),

    // PARTNERSHIP ERRORS
    PARTNERSHIP_EMAIL_ALREADY_REGISTERED("PARTNER-001",
            "Email này đã đăng ký tài khoản. Vui lòng đăng nhập để gửi yêu cầu hợp tác.",
            HttpStatus.BAD_REQUEST),
    PARTNERSHIP_REQUEST_NOT_FOUND("PARTNER-002", "Không tìm thấy thông tin yêu cầu hợp tác.", HttpStatus.NOT_FOUND),
    INVALID_PARTNERSHIP_ROLE("PARTNER-003",
            "Vai trò yêu cầu hợp tác phải là Nhà đăng ký gian hàng (Exhibitor) hoặc Nhà tổ chức (Organizer).",
            HttpStatus.BAD_REQUEST),
    INVALID_PARTNERSHIP_REQUEST_STATUS("PARTNER-004", "Trạng thái yêu cầu hợp tác không hợp lệ.",
            HttpStatus.BAD_REQUEST),
    PARTNERSHIP_REQUEST_ALREADY_PENDING("PARTNER-005",
            "Bạn đang có một yêu cầu hợp tác đang chờ duyệt. Vui lòng chờ quản trị viên xử lý.",
            HttpStatus.BAD_REQUEST),
    PARTNERSHIP_REQUESTER_EMAIL_MUST_MATCH_AUTHENTICATED_USER("PARTNER-006",
            "Email liên hệ phải trùng với email tài khoản đang đăng nhập. Vui lòng đăng xuất nếu muốn gửi yêu cầu cho email khác.",
            HttpStatus.BAD_REQUEST),
    PARTNERSHIP_REQUEST_AWAITING_VERIFICATION("PARTNER-007",
            "Yêu cầu hợp tác đang chờ xác thực qua email. Vui lòng kiểm tra hộp thư của bạn.",
            HttpStatus.BAD_REQUEST),
    PARTNERSHIP_POLICY_ACCEPTANCE_REQUIRED("PARTNER-008",
            "Bạn phải đồng ý với chính sách trước khi gửi yêu cầu hợp tác.",
            HttpStatus.UNPROCESSABLE_CONTENT),

    // COMPANY ERRORS
    COMPANY_NOT_FOUND("COMPANY-001", "Không tìm thấy thông tin doanh nghiệp.", HttpStatus.NOT_FOUND),
    COMPANY_PROFILE_INCOMPLETE("COMPANY-002", "Vui lòng hoàn thiện hồ sơ doanh nghiệp trước khi sử dụng tính năng này.",
            HttpStatus.FORBIDDEN),
    COMPANY_ARCHIVED("COMPANY-003", "Doanh nghiệp đã ngừng hoạt động, không thể thực hiện thao tác này.",
            HttpStatus.FORBIDDEN),
    COMPANY_NAME_REQUIRED("COMPANY-004", "Tên doanh nghiệp là bắt buộc.", HttpStatus.UNPROCESSABLE_CONTENT),

    // PRODUCT ERRORS
    PRODUCT_NOT_FOUND("PRODUCT-001", "Không tìm thấy thông tin sản phẩm.", HttpStatus.NOT_FOUND),
    PRODUCT_CATEGORY_NOT_FOUND("PRODUCT-002", "Không tìm thấy danh mục sản phẩm.", HttpStatus.NOT_FOUND),
    PRODUCT_SKU_DUPLICATED("PRODUCT-003", "Mã sản phẩm (SKU) đã tồn tại trong hệ thống.", HttpStatus.CONFLICT),
    PRODUCT_CATEGORY_NAME_DUPLICATED("PRODUCT-004", "Tên danh mục sản phẩm đã tồn tại.", HttpStatus.CONFLICT),
    INVALID_PRODUCT_MEDIA("PRODUCT-005", "Hình ảnh hoặc video của sản phẩm không hợp lệ.", HttpStatus.BAD_REQUEST),
    INVALID_PRODUCT_CATEGORY_STATUS("PRODUCT-006", "Trạng thái danh mục sản phẩm không hợp lệ.",
            HttpStatus.BAD_REQUEST),
    INVALID_PRODUCT_STATUS("PRODUCT-007", "Trạng thái sản phẩm không hợp lệ.", HttpStatus.BAD_REQUEST),
    PRODUCT_USED_BY_PENDING_BOOTH("PRODUCT-008",
            "Sản phẩm đang được sử dụng bởi một gian hàng đang chờ duyệt hoặc đã xuất bản, không thể chỉnh sửa hoặc xóa.",
            HttpStatus.CONFLICT),
    PRODUCT_MEDIA_REFERENCE_INVALID("PRODUCT-009", "Tệp phương tiện được tham chiếu không thuộc sản phẩm này.",
            HttpStatus.BAD_REQUEST),
    PRODUCT_MEDIA_LIMIT_EXCEEDED("PRODUCT-010", "Số lượng hình ảnh hoặc video của sản phẩm vượt quá giới hạn cho phép.",
            HttpStatus.BAD_REQUEST),

    // BOOTH ERRORS
    BOOTH_TEMPLATE_NOT_FOUND("BOOTH-001", "Không tìm thấy mẫu gian hàng (booth template).", HttpStatus.NOT_FOUND),
    INVALID_BOOTH_TEMPLATE("BOOTH-002", "Mẫu gian hàng không hợp lệ.", HttpStatus.BAD_REQUEST),
    INVALID_PANORAMA_HOTSPOT("BOOTH-003", "Điểm tương tác (hotspot) trên ảnh 360 không hợp lệ.",
            HttpStatus.BAD_REQUEST),
    PANORAMA_FILE_INVALID("BOOTH-004", "Tệp ảnh panorama không hợp lệ.", HttpStatus.BAD_REQUEST),
    PANORAMA_FILE_SAVE_FAILED("BOOTH-005", "Không thể lưu tệp ảnh panorama. Vui lòng thử lại.",
            HttpStatus.INTERNAL_SERVER_ERROR),
    BOOTH_NOT_FOUND("BOOTH-006", "Không tìm thấy thông tin gian hàng.", HttpStatus.NOT_FOUND),
    INVALID_BOOTH("BOOTH-007", "Thông tin gian hàng không hợp lệ.", HttpStatus.BAD_REQUEST),
    PANORAMA_NOT_FOUND("BOOTH-008", "Không tìm thấy ảnh panorama 360.", HttpStatus.NOT_FOUND),
    HOTSPOT_NOT_FOUND("BOOTH-009", "Không tìm thấy điểm tương tác (hotspot).", HttpStatus.NOT_FOUND),
    INVALID_HOTSPOT("BOOTH-010", "Thông tin điểm tương tác (hotspot) không hợp lệ.", HttpStatus.BAD_REQUEST),
    MEDIA_ASSET_NOT_FOUND("BOOTH-011", "Không tìm thấy tệp phương tiện (hình ảnh/video).", HttpStatus.NOT_FOUND),
    INVALID_MEDIA_ASSET("BOOTH-012", "Tệp phương tiện không hợp lệ.", HttpStatus.BAD_REQUEST),
    BOOTH_QUOTA_EXCEEDED("BOOTH-013", "Đã vượt quá số lượng gian hàng cho phép trong gói dịch vụ.",
            HttpStatus.BAD_REQUEST),
    BOOTH_TEMPLATE_NOT_COMPATIBLE("BOOTH-014", "Mẫu gian hàng không tương thích với gói đăng ký của bạn.",
            HttpStatus.BAD_REQUEST),
    BOOTH_NOT_EDITABLE("BOOTH-015", "Gian hàng không thể chỉnh sửa ở trạng thái hiện tại.", HttpStatus.BAD_REQUEST),
    INVALID_BOOTH_REVIEW_STATUS("BOOTH-016", "Trạng thái xét duyệt gian hàng không hợp lệ.", HttpStatus.BAD_REQUEST),
    BOOTH_REVIEW_DEADLINE_PASSED("BOOTH-017", "Đã quá hạn chót gửi yêu cầu xét duyệt gian hàng.",
            HttpStatus.BAD_REQUEST),
    BOOTH_REVIEW_ALREADY_PENDING("BOOTH-018", "Yêu cầu xét duyệt gian hàng đang được xử lý.", HttpStatus.BAD_REQUEST),
    BOOTH_REVIEW_REQUEST_NOT_FOUND("BOOTH-019", "Không tìm thấy yêu cầu xét duyệt gian hàng.", HttpStatus.NOT_FOUND),
    BOOTH_DRAFT_NOT_REVIEWABLE("BOOTH-020", "Bản thiết kế gian hàng chưa sẵn sàng để xét duyệt.", HttpStatus.FORBIDDEN),
    BOOTH_TEMPLATE_REQUIRES_EMPTY_BOOTH("BOOTH-021",
            "Gian hàng phải chưa có ảnh panorama trước khi áp dụng mẫu thiết kế.",
            HttpStatus.CONFLICT),
    BOOTH_REVIEW_NO_CHANGES_AFTER_REJECTION("BOOTH-022",
            "Gian hàng không có thay đổi so với phiên bản bị từ chối gần nhất. Vui lòng chỉnh sửa trước khi gửi lại.",
            HttpStatus.CONFLICT),
    BOOTH_NAME_REQUIRED("BOOTH-023", "Tên gian hàng là bắt buộc.", HttpStatus.BAD_REQUEST),
    BOOTH_THUMBNAIL_INVALID("BOOTH-024", "Ảnh đại diện gian hàng không hợp lệ.", HttpStatus.BAD_REQUEST),
    BOOTH_PANORAMA_LIMIT_EXCEEDED("BOOTH-025", "Số lượng panorama của gian hàng vượt quá giới hạn cho phép.",
            HttpStatus.BAD_REQUEST),
    BOOTH_HOTSPOT_LIMIT_EXCEEDED("BOOTH-026", "Số lượng hotspot của gian hàng vượt quá giới hạn cho phép.",
            HttpStatus.BAD_REQUEST),
    BOOTH_PRODUCT_LIMIT_EXCEEDED("BOOTH-027", "Số lượng sản phẩm trong gian hàng vượt quá giới hạn cho phép.",
            HttpStatus.BAD_REQUEST),
    BOOTH_EMBEDDED_VIDEO_LIMIT_EXCEEDED("BOOTH-028", "Số lượng video nhúng trong gian hàng vượt quá giới hạn cho phép.",
            HttpStatus.BAD_REQUEST),
    BOOTH_REVIEW_REJECTION_REASON_REQUIRED("BOOTH-029", "Lý do từ chối gian hàng là bắt buộc.",
            HttpStatus.BAD_REQUEST),
    MEDIA_ASSET_FILTER_INVALID("BOOTH-030", "Bộ lọc loại tệp phương tiện không hợp lệ.", HttpStatus.BAD_REQUEST),
    MEDIA_ASSET_NAME_INVALID("BOOTH-031", "Tên tệp phương tiện không hợp lệ.", HttpStatus.BAD_REQUEST),
    MEDIA_ASSET_FILE_INVALID("BOOTH-032", "Tệp phương tiện tải lên không hợp lệ.", HttpStatus.BAD_REQUEST),
    MEDIA_ASSET_IN_USE("BOOTH-033", "Tệp phương tiện đang được sử dụng và không thể xóa.", HttpStatus.BAD_REQUEST),
    HOTSPOT_REQUEST_INVALID("BOOTH-034", "Thông tin bắt buộc của hotspot không hợp lệ.", HttpStatus.BAD_REQUEST),
    HOTSPOT_NAV_TARGET_REQUIRED("BOOTH-035", "Hotspot điều hướng phải chỉ định panorama đích.", HttpStatus.BAD_REQUEST),
    HOTSPOT_PRODUCT_REQUIRED("BOOTH-036", "Hotspot sản phẩm phải chỉ định sản phẩm.", HttpStatus.BAD_REQUEST),
    HOTSPOT_INFO_CONTENT_INVALID("BOOTH-037", "Nội dung hotspot thông tin không hợp lệ.", HttpStatus.BAD_REQUEST),
    HOTSPOT_MEDIA_REQUIRED("BOOTH-038", "Hotspot phương tiện phải chỉ định tệp phương tiện.", HttpStatus.BAD_REQUEST),
    HOTSPOT_MEDIA_TYPE_INVALID("BOOTH-039", "Loại tệp phương tiện không phù hợp với hotspot.", HttpStatus.BAD_REQUEST),
    HOTSPOT_CORNERS_INVALID("BOOTH-040", "Tọa độ các góc của hotspot không hợp lệ.", HttpStatus.BAD_REQUEST),
    HOTSPOT_NAME_REQUIRED("BOOTH-041", "Tên hotspot là bắt buộc.", HttpStatus.BAD_REQUEST),
    BOOTH_TEMPLATE_NAME_REQUIRED("BOOTH-042", "Tên mẫu gian hàng là bắt buộc.", HttpStatus.BAD_REQUEST),
    BOOTH_TEMPLATE_PANORAMA_REQUIRED("BOOTH-043", "Mẫu gian hàng phải có ít nhất một panorama.",
            HttpStatus.BAD_REQUEST),
    BOOTH_TEMPLATE_PANORAMA_INVALID("BOOTH-044", "Dữ liệu panorama của mẫu gian hàng không hợp lệ.",
            HttpStatus.BAD_REQUEST),
    BOOTH_TEMPLATE_PANORAMA_KEY_DUPLICATED("BOOTH-045", "Khóa panorama trong mẫu gian hàng bị trùng.",
            HttpStatus.BAD_REQUEST),
    BOOTH_TEMPLATE_DEFAULT_PANORAMA_INVALID("BOOTH-046", "Mẫu gian hàng phải có đúng một panorama mặc định.",
            HttpStatus.BAD_REQUEST),
    BOOTH_TEMPLATE_STATUS_INVALID("BOOTH-047", "Trạng thái mẫu gian hàng không hợp lệ cho thao tác này.",
            HttpStatus.BAD_REQUEST),
    BOOTH_TEMPLATE_THUMBNAIL_INVALID("BOOTH-048", "Ảnh đại diện mẫu gian hàng không hợp lệ.",
            HttpStatus.BAD_REQUEST),
    BOOTH_TEMPLATE_HOTSPOT_INVALID("BOOTH-049", "Dữ liệu hotspot trong mẫu gian hàng không hợp lệ.",
            HttpStatus.BAD_REQUEST),
    BOOTH_TEMPLATE_NAVIGATION_REQUIRED("BOOTH-050", "Mẫu có nhiều panorama phải có hotspot điều hướng.",
            HttpStatus.BAD_REQUEST),
    BOOTH_TEMPLATE_PANORAMA_UNREACHABLE("BOOTH-051", "Có panorama không thể truy cập từ panorama mặc định.",
            HttpStatus.BAD_REQUEST),

    // DESIGN REQUEST ERRORS
    DESIGN_REQUEST_NOT_FOUND("DESIGN-001", "Không tìm thấy yêu cầu thiết kế.", HttpStatus.NOT_FOUND),
    INVALID_DESIGN_REQUEST_STATUS("DESIGN-002", "Trạng thái yêu cầu thiết kế không hợp lệ.", HttpStatus.BAD_REQUEST),
    DESIGN_REQUEST_QUOTA_EXCEEDED("DESIGN-003", "Đã hết số lượt yêu cầu thiết kế cho phép cho gian hàng này.",
            HttpStatus.BAD_REQUEST),
    DESIGNER_WORKLOAD_EXCEEDED("DESIGN-004", "Nhà thiết kế đã đạt giới hạn tối đa số lượng công việc đang xử lý.",
            HttpStatus.BAD_REQUEST),
    INVALID_DESIGNER("DESIGN-005", "Người dùng được chỉ định không có vai trò Nhà thiết kế (Designer).",
            HttpStatus.BAD_REQUEST),
    INVALID_DESIGN_DRAFT("DESIGN-006", "Bản thiết kế nháp không hợp lệ.", HttpStatus.BAD_REQUEST),
    DESIGN_REQUEST_NOT_ELIGIBLE("DESIGN-007", "Gian hàng chưa đủ điều kiện cho yêu cầu thiết kế này.",
            HttpStatus.CONFLICT),
    DESIGN_PRODUCT_ACCESS_FORBIDDEN("DESIGN-008", "Không thể truy cập sản phẩm cho yêu cầu thiết kế này.",
            HttpStatus.FORBIDDEN),
    DESIGN_PRODUCT_NOT_ALLOWED("DESIGN-009", "Sản phẩm này không nằm trong danh sách cho phép thiết kế.",
            HttpStatus.FORBIDDEN),
    DESIGN_PRODUCT_LOCKED("DESIGN-010", "Sản phẩm đang được sử dụng ở một yêu cầu thiết kế khác.", HttpStatus.CONFLICT),
    DESIGN_CANCELLATION_PENDING("DESIGN-011", "Yêu cầu hủy thiết kế đang chờ quản trị viên phê duyệt.",
            HttpStatus.CONFLICT),
    DESIGN_MEDIA_ASSET_NOT_ALLOWED("DESIGN-013", "Tệp phương tiện này không nằm trong danh sách cho phép thiết kế.",
            HttpStatus.FORBIDDEN),
    DESIGN_MEDIA_ASSET_LOCKED("DESIGN-014", "Tệp phương tiện đang được sử dụng ở một yêu cầu thiết kế.",
            HttpStatus.CONFLICT),
    DESIGN_DRAFT_NOT_FOUND("DESIGN-015", "Không tìm thấy bản thiết kế nháp.", HttpStatus.BAD_REQUEST),
    DESIGN_DRAFT_ALREADY_EXISTS("DESIGN-016", "Yêu cầu thiết kế đã có bản nháp đang làm việc.", HttpStatus.BAD_REQUEST),
    DESIGN_DRAFT_NOT_EDITABLE("DESIGN-017", "Bản thiết kế nháp không thể chỉnh sửa ở trạng thái hiện tại.",
            HttpStatus.BAD_REQUEST),
    DESIGN_DRAFT_VERSION_INVALID("DESIGN-018", "Phiên bản bản thiết kế nháp không hợp lệ.", HttpStatus.BAD_REQUEST),
    DESIGN_DRAFT_REQUEST_INVALID("DESIGN-019", "Yêu cầu cập nhật bản thiết kế nháp không hợp lệ.",
            HttpStatus.BAD_REQUEST),
    DESIGN_DRAFT_GRAPH_INVALID("DESIGN-020", "Bản thiết kế nháp không thuộc yêu cầu thiết kế này.",
            HttpStatus.BAD_REQUEST),
    DESIGN_DRAFT_PANORAMA_INVALID("DESIGN-021", "Dữ liệu panorama trong bản thiết kế nháp không hợp lệ.",
            HttpStatus.BAD_REQUEST),
    DESIGN_DRAFT_PANORAMA_ORDER_INVALID("DESIGN-022", "Thứ tự panorama trong bản thiết kế nháp không hợp lệ.",
            HttpStatus.BAD_REQUEST),
    DESIGN_DRAFT_DEFAULT_PANORAMA_INVALID("DESIGN-023", "Bản thiết kế nháp phải có đúng một panorama mặc định.",
            HttpStatus.BAD_REQUEST),
    DESIGN_DRAFT_HOTSPOT_INVALID("DESIGN-024", "Dữ liệu hotspot trong bản thiết kế nháp không hợp lệ.",
            HttpStatus.BAD_REQUEST),
    DESIGN_DRAFT_HOTSPOT_REFERENCE_INVALID("DESIGN-025", "Tham chiếu của hotspot trong bản thiết kế nháp không hợp lệ.",
            HttpStatus.BAD_REQUEST),
    DESIGN_DRAFT_PRODUCT_REFERENCE_INVALID("DESIGN-026",
            "Sản phẩm được tham chiếu trong bản thiết kế nháp không hợp lệ.",
            HttpStatus.BAD_REQUEST),
    DESIGN_DRAFT_MEDIA_REFERENCE_INVALID("DESIGN-027",
            "Tệp phương tiện được tham chiếu trong bản thiết kế nháp không hợp lệ.",
            HttpStatus.BAD_REQUEST),
    DESIGN_DRAFT_MEDIA_IN_USE("DESIGN-028", "Tệp phương tiện đang được bản thiết kế sử dụng và không thể xóa.",
            HttpStatus.BAD_REQUEST),
    DESIGN_DRAFT_MEDIA_DUPLICATED("DESIGN-029", "Tệp phương tiện đã tồn tại trong bản thiết kế nháp.",
            HttpStatus.BAD_REQUEST),
    DESIGN_DRAFT_MEDIA_ORDER_INVALID("DESIGN-030", "Thứ tự tệp phương tiện trong bản thiết kế nháp không hợp lệ.",
            HttpStatus.BAD_REQUEST),
    DESIGN_DRAFT_ASSET_NOT_FOUND("DESIGN-031", "Không tìm thấy tài nguyên của bản thiết kế nháp.",
            HttpStatus.BAD_REQUEST),
    DESIGN_DRAFT_ASSET_TYPE_INVALID("DESIGN-032", "Loại tài nguyên của bản thiết kế nháp không hợp lệ.",
            HttpStatus.BAD_REQUEST),
    DESIGN_DRAFT_ASSET_NAME_INVALID("DESIGN-033", "Tên tài nguyên của bản thiết kế nháp không hợp lệ.",
            HttpStatus.BAD_REQUEST),
    DESIGN_DRAFT_SETTINGS_INVALID("DESIGN-034", "Cấu hình bản thiết kế nháp không hợp lệ.", HttpStatus.BAD_REQUEST),
    DESIGN_DRAFT_REVIEW_NOTE_REQUIRED("DESIGN-035", "Nội dung nhận xét bản thiết kế là bắt buộc.",
            HttpStatus.BAD_REQUEST),
    DESIGN_CANCELLATION_REASON_REQUIRED("DESIGN-036", "Lý do yêu cầu hủy thiết kế là bắt buộc.",
            HttpStatus.BAD_REQUEST),
    DESIGN_CONTACT_EMAIL_INVALID("DESIGN-037", "Email liên hệ của yêu cầu thiết kế không hợp lệ.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    DESIGN_CONTACT_PHONE_INVALID("DESIGN-038", "Số điện thoại liên hệ của yêu cầu thiết kế không hợp lệ.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    DESIGN_MEDIA_ASSET_FILTER_INVALID("DESIGN-039", "Bộ lọc loại tệp phương tiện thiết kế không hợp lệ.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    DESIGN_BASELINE_PRODUCT_INVALID("DESIGN-040", "Sản phẩm hiện có của gian hàng không còn hợp lệ để thiết kế.",
            HttpStatus.CONFLICT),
    DESIGN_BASELINE_MEDIA_INVALID("DESIGN-041", "Tệp phương tiện hiện có của gian hàng không hợp lệ để thiết kế.",
            HttpStatus.CONFLICT),
    DESIGN_REQUEST_BOOTH_STATE_INVALID("DESIGN-042", "Trạng thái gian hàng không phù hợp với yêu cầu thiết kế.",
            HttpStatus.CONFLICT),
    DESIGN_REQUEST_EXHIBITION_NOT_ELIGIBLE("DESIGN-043", "Triển lãm không ở trạng thái cho phép tiếp tục thiết kế.",
            HttpStatus.CONFLICT),

    // PACKAGE TEMPLATE ERRORS
    PACKAGE_TEMPLATE_NOT_FOUND("PACKAGE-001", "Không tìm thấy mẫu gói dịch vụ.", HttpStatus.NOT_FOUND),
    PACKAGE_TEMPLATE_NAME_DUPLICATED("PACKAGE-002", "Tên mẫu gói dịch vụ đã tồn tại.", HttpStatus.CONFLICT),

    // EXHIBITION ERRORS
    EXHIBITION_NOT_FOUND("EXHIBITION-001", "Không tìm thấy thông tin triển lãm.", HttpStatus.NOT_FOUND),
    EXHIBITION_PACKAGE_NOT_FOUND("EXHIBITION-002", "Không tìm thấy gói triển lãm.", HttpStatus.NOT_FOUND),
    EXHIBITION_LIMIT_EXCEEDED("EXHIBITION-003",
            "Mỗi nhà tổ chức chỉ được có tối đa 3 đơn đăng ký ở trạng thái chờ duyệt đồng thời.",
            HttpStatus.BAD_REQUEST),
    EXHIBITION_CANNOT_CANCEL("EXHIBITION-004", "Không thể hủy lượt đăng ký ở trạng thái hiện tại.",
            HttpStatus.BAD_REQUEST),
    EXHIBITION_INVALID_STATUS("EXHIBITION-005", "Trạng thái đơn đăng ký triển lãm không hợp lệ cho thao tác này.",
            HttpStatus.BAD_REQUEST),
    EXHIBITION_ALREADY_REVIEWED("EXHIBITION-006", "Đơn đăng ký triển lãm đã được xử lý trước đó.",
            HttpStatus.BAD_REQUEST),
    EXHIBITION_NAME_DUPLICATED("EXHIBITION-007", "Tên triển lãm đã được sử dụng.", HttpStatus.CONFLICT),
    EXHIBITION_DETAILS_CHANGES_NOT_ALLOWED("EXHIBITION-008",
            "Chỉ có thể chỉnh sửa hồ sơ khi đang chờ duyệt hoặc đã bị từ chối.",
            HttpStatus.BAD_REQUEST),
    EXHIBITION_RESUBMISSION_LIMIT_REACHED("EXHIBITION-009",
            "Hồ sơ đã đạt số lần gửi lại tối đa. Vui lòng liên hệ bộ phận hỗ trợ.",
            HttpStatus.BAD_REQUEST),
    EXHIBITION_ALREADY_STARTED("EXHIBITION-010", "Không thể chỉnh sửa vì triển lãm đã bắt đầu.",
            HttpStatus.BAD_REQUEST),
    EXHIBITION_HAS_REGISTRATIONS("EXHIBITION-011",
            "Không thể chỉnh sửa thông tin vì đã có doanh nghiệp đăng ký tham gia.",
            HttpStatus.BAD_REQUEST),
    EXHIBITION_ASSET_CHANGES_NOT_ALLOWED("EXHIBITION-012",
            "Chỉ có thể cập nhật tài liệu truyền thông sau khi hồ sơ được duyệt.",
            HttpStatus.BAD_REQUEST),
    EXHIBITION_APPROVAL_LEAD_TIME_NOT_MET("EXHIBITION-013",
            "Chưa thể duyệt hồ sơ vì ngày bắt đầu quá gần. Vui lòng yêu cầu nhà tổ chức điều chỉnh thời gian.",
            HttpStatus.BAD_REQUEST),
    EXHIBITION_PACKAGE_CHANGES_NOT_ALLOWED("EXHIBITION-014",
            "Chỉ có thể thay đổi gói dịch vụ khi hồ sơ đang chờ duyệt hoặc đã bị từ chối.",
            HttpStatus.BAD_REQUEST),
    EXHIBITION_PACKAGE_IN_USE("EXHIBITION-015",
            "Không thể sửa hoặc xóa gói dịch vụ vì đã có doanh nghiệp đăng ký gói này.",
            HttpStatus.BAD_REQUEST),
    EXHIBITION_NOT_READY_TO_PUBLISH("EXHIBITION-016",
            "Chỉ có thể công bố triển lãm sau khi hồ sơ đã được duyệt và mở đăng ký.",
            HttpStatus.BAD_REQUEST),
    EXHIBITION_SPONSOR_CHANGES_NOT_ALLOWED("EXHIBITION-017",
            "Chỉ có thể thay đổi nhà tài trợ khi hồ sơ đang chờ duyệt hoặc đã bị từ chối.",
            HttpStatus.BAD_REQUEST),
    EXHIBITION_SPONSOR_LIMIT_EXCEEDED("EXHIBITION-018", "Số lượng nhà tài trợ vượt quá giới hạn cho phép.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    EXHIBITION_SPONSOR_INPUT_MISMATCH("EXHIBITION-019", "Số lượng tên nhà tài trợ và logo không khớp.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    EXHIBITION_DATE_RANGE_INVALID("EXHIBITION-020", "Ngày kết thúc triển lãm không được trước ngày bắt đầu.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    EXHIBITION_DURATION_EXCEEDED("EXHIBITION-021", "Thời lượng triển lãm vượt quá giới hạn cho phép.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    EXHIBITION_START_LEAD_TIME_NOT_MET("EXHIBITION-022",
            "Ngày bắt đầu triển lãm không đáp ứng thời gian chuẩn bị tối thiểu.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    EXHIBITION_PACKAGE_PRICE_BELOW_MINIMUM("EXHIBITION-023", "Giá gói triển lãm thấp hơn mức giá tối thiểu.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    EXHIBITION_PACKAGE_ALREADY_CONFIGURED("EXHIBITION-024", "Mẫu gói dịch vụ đã được cấu hình cho triển lãm này.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    EXHIBITION_IMAGE_REQUIRED("EXHIBITION-025", "Ảnh triển lãm là bắt buộc.", HttpStatus.UNPROCESSABLE_CONTENT),
    EXHIBITION_PACKAGE_COUNT_INVALID("EXHIBITION-026", "Triển lãm phải có từ một đến ba gói dịch vụ.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    EXHIBITION_PACKAGE_CONFIGURATION_INVALID("EXHIBITION-027", "Thông tin cấu hình gói triển lãm không hợp lệ.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    EXHIBITION_PACKAGE_PRIORITY_DUPLICATED("EXHIBITION-028", "Độ ưu tiên hiển thị của gói triển lãm bị trùng.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    EXHIBITION_PACKAGE_INACTIVE("EXHIBITION-029", "Gói triển lãm không ở trạng thái hoạt động.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    EXHIBITION_PACKAGE_TEMPLATE_INACTIVE("EXHIBITION-030",
            "Mẫu gói dịch vụ của triển lãm không ở trạng thái hoạt động.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    EXHIBITION_SPONSOR_ASSET_NOT_FOUND("EXHIBITION-031", "Không tìm thấy logo nhà tài trợ.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    EXHIBITION_SPONSOR_ASSET_INVALID("EXHIBITION-032", "Logo nhà tài trợ không thuộc triển lãm này.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    EXHIBITION_PACKAGE_OWNERSHIP_INVALID("EXHIBITION-033", "Gói dịch vụ không thuộc triển lãm này.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    REGISTRATION_NOT_FOUND("REGISTRATION-001", "Không tìm thấy thông tin lượt đăng ký.", HttpStatus.NOT_FOUND),
    REGISTRATION_DEPENDENCY_INVALID("REGISTRATION-003",
            "Không thể tiếp tục xử lý lượt đăng ký này. Vui lòng liên hệ bộ phận hỗ trợ.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    REGISTRATION_CLOSED("REGISTRATION-004", "Triển lãm hiện không nhận thêm đăng ký.", HttpStatus.BAD_REQUEST),
    REGISTRATION_ALREADY_PAID("REGISTRATION-005",
            "Không thể hủy lượt đăng ký đã thanh toán. Vui lòng liên hệ ban tổ chức nếu cần hỗ trợ.",
            HttpStatus.BAD_REQUEST),
    EXHIBITION_PACKAGE_FULL("REGISTRATION-006",
            "Gói dịch vụ đã hết số lượng gian hàng cho phép.",
            HttpStatus.BAD_REQUEST),
    REGISTRATION_RESERVATION_EXPIRED("REGISTRATION-007",
            "Thời gian giữ chỗ thanh toán cho đăng ký này đã hết hạn.",
            HttpStatus.BAD_REQUEST),
    REGISTRATION_COMPANY_MISSING("REGISTRATION-006", "Lượt đăng ký thiếu thông tin dFoanh nghiệp.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    REGISTRATION_COMPANY_OWNER_MISSING("REGISTRATION-007", "Doanh nghiệp của lượt đăng ký thiếu thông tin chủ sở hữu.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    REGISTRATION_PACKAGE_MISSING("REGISTRATION-008", "Lượt đăng ký thiếu thông tin gói triển lãm.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    REGISTRATION_EXHIBITION_MISSING("REGISTRATION-009", "Lượt đăng ký thiếu thông tin triển lãm.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    REGISTRATION_BENEFIT_LIMITS_INVALID("REGISTRATION-010", "Giới hạn quyền lợi của lượt đăng ký không hợp lệ.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    REGISTRATION_INVALID_STATUS("REGISTRATION-011", "Trạng thái lượt đăng ký không hợp lệ cho thao tác này.",
            HttpStatus.UNPROCESSABLE_CONTENT),
    REGISTRATION_REJECTION_REASON_REQUIRED("REGISTRATION-012", "Lý do từ chối lượt đăng ký là bắt buộc.",
            HttpStatus.UNPROCESSABLE_CONTENT),

    // PAYMENT ERRORS
    PAYMENT_LINK_UNAVAILABLE("PAYMENT-001", "Chưa thể tạo liên kết thanh toán. Vui lòng thử lại sau.",
            HttpStatus.BAD_REQUEST),

    // LEAD ERRORS
    LEAD_NOT_FOUND("LEAD-001", "Không tìm thấy thông tin khách hàng tiềm năng.", HttpStatus.NOT_FOUND),

    // CHAT ERRORS
    CHAT_ROOM_NOT_FOUND("CHAT-001", "Không tìm thấy phòng trò chuyện.", HttpStatus.NOT_FOUND),

    // WALLET & WITHDRAWAL ERRORS
    WALLET_NOT_FOUND("WALLET-001", "Không tìm thấy ví doanh nghiệp.", HttpStatus.NOT_FOUND),
    INSUFFICIENT_WALLET_BALANCE("WALLET-002", "Số dư khả dụng không đủ để thực hiện giao dịch.",
            HttpStatus.BAD_REQUEST),
    WITHDRAWAL_AMOUNT_BELOW_MINIMUM("WALLET-003", "Số tiền rút phải đạt tối thiểu 100.000 VND.",
            HttpStatus.BAD_REQUEST),
    ACTIVE_WITHDRAWAL_EXISTS("WALLET-004", "Doanh nghiệp đang có một yêu cầu rút tiền chưa hoàn tất.",
            HttpStatus.CONFLICT),
    PAYOUT_PROFILE_NOT_VERIFIED("WALLET-005", "Thông tin tài khoản nhận tiền chưa được xác minh bởi quản trị viên.",
            HttpStatus.BAD_REQUEST),
    PAYOUT_PROFILE_NOT_FOUND("WALLET-006", "Chưa có thông tin tài khoản nhận tiền.", HttpStatus.NOT_FOUND),
    WITHDRAWAL_REQUEST_NOT_FOUND("WALLET-007", "Không tìm thấy yêu cầu rút tiền.", HttpStatus.NOT_FOUND),
    INVALID_WITHDRAWAL_TRANSITION("WALLET-008", "Thao tác không hợp lệ đối với trạng thái yêu cầu rút tiền hiện tại.",
            HttpStatus.BAD_REQUEST),
    TRANSFER_REFERENCE_DUPLICATED("WALLET-009", "Mã giao dịch chuyển khoản đã tồn tại trong hệ thống.",
            HttpStatus.CONFLICT),
    PAYMENT_NOT_CREDITED("WALLET-010", "Giao dịch thanh toán chưa được ghi nhận doanh thu vào ví.",
            HttpStatus.BAD_REQUEST),
    PAYMENT_ALREADY_RELEASED("WALLET-011",
            "Khoản thanh toán đã được giải phóng sang số dư khả dụng, không thể đảo tiền pending.",
            HttpStatus.BAD_REQUEST),
    ENCRYPTION_KEY_INVALID("WALLET-012",
            "Phiên bản khóa mã hóa không hợp lệ hoặc không được hỗ trợ.",
            HttpStatus.INTERNAL_SERVER_ERROR);

    private final String code;
    private final String message;
    private final HttpStatus httpStatus;

    ErrorCode(String code, String message, HttpStatus httpStatus) {
        this.code = code;
        this.message = message;
        this.httpStatus = httpStatus;
    }
}
